_extends: .github

repository:
  name: base
  description: Base repository with default settings and configs
  homepage: github.com

  # A comma-separated list of topics to set on the repository
  topics: settings
  private: false
