repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/bjd2385/circleci-orb-pre-commit-hook
    rev: v1.2.0
    hooks:
      - id: circleci-orb-validate
        args:
          - src # Target the src/ directory.
          - "true" # Enable pre-pack prior to validation.

  - repo: https://github.com/bjd2385/circleci-config-pre-commit-hook
    rev: v1.0.3
    hooks:
      - id: circleci-config-validate
