version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:stable

commands:
  increment-minor-tag:
    steps:
      - run:
          name: Autoincrement repository's latest tag minor version
          command: |+
            git fetch --all --tags
            RES="$(git show-ref --tags)"

            if [ -z "$RES" ]; then
                NEW_TAG="v1.0.0"
            else
                mapfile -d " " -t LATEST_TAG < <(git tag | sort -V | tail -1 | sed 's/\./ /g')

                if [ "${#LATEST_TAG[@]}" -ne 3 ]; then
                    printf "Must follow semver convention /v?[0-9]{3}.[0-9]{3}.[0-9]{3}/ to parse.\\n" 1>&2
                    exit 1
                fi

                one="${LATEST_TAG[0]//v/}"
                two="${LATEST_TAG[1]}"
                three="${LATEST_TAG[2]}"

                # Increment versions mod 1k.
                if [ "$three" == "999" ]; then
                    if [ "$two" == "999" ]; then
                        three=0
                        two=0
                        ((one++))
                    else
                        ((two++))
                        three=0
                    fi
                elif [ "$two" == "999" ] && [ "$three" == "999" ]; then
                    ((one++))
                    two=0
                else
                    ((three++))
                fi

                NEW_TAG="v${one}.${two}.${three}"
            fi

            git tag "$NEW_TAG"
            git push origin "$NEW_TAG"

  release:
    steps:
      - run:
          name: Generate release
          command: |+
            # Get latest tag.
            git fetch --all --tags
            export LATEST_TAG="$(git tag | sort -V | tail -1)"
            echo "$LATEST_TAG"

            # Generate release from tag.
            echo "$GITHUB_TOKEN" | gh auth login --with-token 2>/dev/null || true
            gh release create "$LATEST_TAG" --generate-notes

jobs:
  autoincrement-minor-tag:
    executor: default
    resource_class: small
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - FIXME
      - increment-minor-tag

  generate-release:
    executor: default
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install gh CLI
          command: |+
            wget https://github.com/cli/cli/releases/download/v2.9.0/gh_2.9.0_linux_amd64.deb -O gh.deb
            sudo dpkg -i gh.deb
      - release

  hello:
    executor: default
    resource_class: small
    steps:
      - run:
          name: Hello
          command: echo hello

workflows:
  version: 2

  on-tag:
    jobs:
      - hello:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

  on-merge:
    jobs:
      # Auto-increment minor tag to kick off on-tag workflow.
      - autoincrement-minor-tag:
          filters:
            branches:
              only: master

      # Generate a release from the latest tag.
      - generate-release:
          context: github
          filters:
            branches:
              only: master
          requires:
            - autoincrement-minor-tag

  on-commit:
    jobs:
      - hello:
          filters:
            branches:
              ignore: master
